CREATE TABLE EMPLOYEE_DETAILS(
	EMP_ID INT NOT NULL PRIMARY KEY,
    EMP_NAME VARCHAR(50) NOT NULL,
    JOB_NAME VARCHAR(50) NOT NULL,
    MANAGER_ID INT NOT NULL,
    HIRE_DATE DATE NOT NULL,
    SALARY INT NOT NULL,
    DEPT_ID INT NOT NULL
);